### ISSUE TITLE
May I have the code for training and evaluation?

### ISSUE THREAD

**Issue by WentangChen** [paulotto/canfnet#2]
Hi:
   Thank you for your excellent work!
   I wanna to evalutae the canfnet, can you please release the code for  training and evaluation?

**Comment by paulotto** [comment]
Hi @WentangChen,

You can now find scripts for training and evaluation in the [train](https://github.com/paulotto/canfnet/tree/799c1b0914b5f4eacf422f3c003bc95aeeb2a787/src/canfnet/scripts/train) folder.

**However, consider that they should just be used as references since they have not been tested with this repository and are poorly documented! Moreover, there will be no support provided for these files.**

Best regards,
Paul
