### ISSUE TITLE
Sensor's Intrinsic parameters

### ISSUE THREAD

**Issue by AmirShahid** [paulotto/canfnet#3]
Thank you for sharing the code. Could you please provide more details on how the [camera intrinsic parameters](https://github.com/paulotto/canfnet/blob/main/src/canfnet/src/canfnet/visuotactile_sensor/params/cam_params_gelsightmini.yaml) were estimated for GS-Mini?

**Comment by paulotto** [comment]
Hi @AmirShahid,

We appreciate your interest. Generally, to estimate the intrinsic camera parameters, you can use a chessboard pattern and the tutorials provided by *OpenCV* (as you might have already seen). Here are some references:
- https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html
- https://learnopencv.com/camera-calibration-using-opencv/

Since we needed both intrinsic **and** extrinsic camera parameters, we printed a calibration object with known dimensions for the estimation, as you can see in the image. 
![cam_calib_obj](https://github.com/paulotto/canfnet/assets/65675744/ab7e1647-e882-4ec5-a690-efb71509cb88)

With the *BlobDetector* and *calibrateCamera* functions of *OpenCV*, both intrinsic and extrinsic parameters were estimated simultaneously with sufficient accuracy. Note that you can define a world frame arbitrarily with this method. 

I hope this will help you, and if you have further questions, let me know.

Best,
Paul
